
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 11 17:57:49 BOT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Parentesis_c = 20;
  public static final int For = 9;
  public static final int Parentesis_a = 19;
  public static final int Suma = 11;
  public static final int Numero = 27;
  public static final int Corchete_c = 24;
  public static final int Op_booleano = 18;
  public static final int ERROR = 30;
  public static final int Corchete_a = 23;
  public static final int Identificador = 26;
  public static final int Comillas = 3;
  public static final int Llave_c = 22;
  public static final int Print = 4;
  public static final int Llave_a = 21;
  public static final int Op_relacional = 16;
  public static final int P_coma = 25;
  public static final int In = 29;
  public static final int EOF = 0;
  public static final int Division = 14;
  public static final int Op_atribucion = 17;
  public static final int Resta = 12;
  public static final int If = 5;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_logico = 15;
  public static final int Do = 7;
  public static final int Igual = 10;
  public static final int While = 8;
  public static final int Multiplicacion = 13;
  public static final int Conector = 28;
}

